### ISSUE TITLE
Overlap on mobile chrome

### ISSUE THREAD

**Issue by jonmcoe** [Naresh1318/Topaz#1]
Saw your HN post and took a look. Noticed a slight overlap of elements here:

![Screenshot_20190808-220742](https://user-images.githubusercontent.com/5412533/62749085-19282e80-ba29-11e9-8818-001948d8ccb1.png)

Pixel 2
Android 9, build PQ3A... 
Chrome 76.0.3809.89

Lovely site!

**Comment by Naresh1318** [comment]
Fixed!
